name: websockets
description: A platform-independent WebSocket library.
version: 0.2.0+2
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-websockets
environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  reflectable: ^0.5.1

dev_dependencies:
  test: any
  browser: any

transformers:
- reflectable:
    entry_points:
      - test/html_test.dart